'use strict';

function detailHeader(title,sub){return `<div class="detail-shell"><div class="detail-head"><button class="back-btn" data-act="back">${icon('back')}</button><div class="title-wrap"><div class="app-mark"><div class="wordmark">ZivugMatch</div><div class="bh">ב״ה</div></div><h1 class="detail-name">${esc(title)}</h1><div class="detail-meta">${esc(sub||'')}</div></div><button class="more-btn" data-act="detail-menu">⋯</button></div>`;}

function sourceDetail(sid){const src=source(sid);if(!src)return shadchanScreen();const st=sourceStats(src),from=person(src.fromPersonId);return `${detailHeader(src.name,`${src.kind||'Source'} · ${fmtDate(src.createdAt)}${from?` · from ${from.name}`:''}`)}<div class="progress-card"><div style="font:700 21px Georgia,serif">${st.total} shadchanim</div><div style="font-size:11px;color:var(--text-2);margin-top:4px">This list updates itself when you contact someone anywhere in the app.</div><div class="progress-line"><i style="width:${st.total?Math.round(st.contacted/st.total*100):0}%"></i></div></div><div class="summary-strip">${summaryCard('sage',st.contacted,'Contacted')}${summaryCard('blue',st.replied,'Replied')}${summaryCard('amber',st.follow,'Contact again')}</div><div class="section-head"><h2>People</h2><span></span></div>${(src.lines||[]).length?`<div class="list-card">${src.lines.map(sourceLineRow).join('')}</div>`:empty('No people in this source','Add people to this list as they are filed.')}`;}
// A line of a list: the person's one record, or the original words when nobody is added for them yet.
function sourceLineRow(l){const p=l.personId&&person(l.personId);return p?personRow(p):`<div class="warm-person-row source-line-unlinked"><div class="warm-avatar sky">?</div><div class="warm-person-main"><div class="warm-person-top"><strong>${esc(l.text||'Unnamed')}</strong></div><div class="warm-person-line">Not added yet</div></div></div>`;}

function entryDetail(eid){const e=data.entries.find(x=>x.id===eid);if(!e)return recentScreen();const from=person(e.fromPersonId),to=person(e.toPersonId);return `${detailHeader(e.type==='message'?e.channel||'Message':e.type==='call'?'Call':e.type==='profile'?'Profile':e.type==='date'?'Date':e.type==='source'?'Source':'Note',`${fmtDate(e.at)} · ${fmtTime(e.at)}`)}<div class="profile-card"><h3>${e.direction==='in'?`${esc(from?.name||'Someone')} → Me`:e.direction==='out'?`Me → ${esc(to?.name||'Someone')}`:'Activity'}</h3><div class="profile-text">${esc(e.text||'')}</div></div>${linkedAbout(e)?`<div class="info-card"><div class="info-row"><div class="info-label">About</div><div class="info-value">${esc(linkedAbout(e))}</div><button class="info-action" data-act="open-about" data-entry-id="${e.id}">Open</button></div>${e.result?`<div class="info-row"><div class="info-label">Result</div><div class="info-value">${esc(e.result)}</div><span></span></div>`:''}</div>`:''}`;}

function render(){applySettings();let body;if(ui.detail?.type==='person')body=personDetail(ui.detail.id);else if(ui.detail?.type==='shidduch')body=shidduchDetail(ui.detail.id);else if(ui.detail?.type==='source')body=sourceDetail(ui.detail.id);else if(ui.detail?.type==='entry')body=entryDetail(ui.detail.id);else if(ui.screen==='recent')body=recentScreen();else if(ui.screen==='guys')body=peopleScreen('Guy');else if(ui.screen==='girls')body=peopleScreen('Girl');else if(ui.screen==='shadchanim')body=shadchanScreen();else body=shidduchimScreen();app.innerHTML=`<main class="page">${body}</main>${nav()}`;queueStickyHeaders();}

function showToast(msg){toastEl.textContent=msg;toastEl.classList.remove('has-action');toastEl.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toastEl.classList.remove('show'),2200);}
function showUndoToast(msg,copyId){if(!copyId)return showToast(msg);showActionToast(msg,{act:'undo-safety',copyId});}
function showActionToast(msg,attrs,label='Undo'){toastEl.innerHTML=`<span>${esc(msg)}</span><button ${Object.entries(attrs).map(([k,v])=>`data-${k.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}="${esc(v)}"`).join(' ')}>${esc(label)}</button>`;toastEl.classList.add('show','has-action');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toastEl.classList.remove('show','has-action'),8000);}
function openSheet(html){overlay.innerHTML=`<div class="scrim"><div class="sheet"><div class="sheet-handle"></div>${html}</div></div>`;}
function closeSheet(){overlay.innerHTML='';}
