function shidduch(sid){return data.shidduchim.find(s=>s.id===sid)}
function round(rid){return data.rounds.find(r=>r.id===rid)}
function dateById(did){return data.dates.find(d=>d.id===did)}
function source(sid){return data.sources.find(s=>s.id===sid)}
function idea(iid){return data.ideas.find(i=>i.id===iid)}
function me(){return data.people.find(p=>p.isMe)||data.people[0]}
function byType(type){return data.people.filter(p=>p.types?.includes(type));}
function entriesForPerson(pid){return data.entries.filter(e=>e.personIds?.includes(pid)).sort((a,b)=>new Date(b.at)-new Date(a.at));}
function entriesForAbout(type,idv){return data.entries.filter(e=>e.aboutType===type&&e.aboutId===idv).sort((a,b)=>new Date(b.at)-new Date(a.at));}
function openForPerson(pid,dir){return data.openItems.filter(x=>x.status==='open'&&x.personId===pid&&(!dir||x.direction===dir));}
function shidduchimForPerson(pid){return data.shidduchim.filter(s=>s.guyId===pid||s.girlId===pid||s.shadchanIds?.includes(pid));}
function ideasForPerson(pid){return data.ideas.filter(i=>i.guyId===pid||i.girlId===pid);}
function lastContact(pid){const e=entriesForPerson(pid).find(x=>['call','message','profile','note'].includes(x.type));return e?.at||null;}
function fmtDay(ts){if(!ts)return'No contact yet';const d=new Date(ts),now=new Date();const diff=Math.floor((now-d)/86400000);if(diff<=0)return'Today';if(diff===1)return'Yesterday';if(diff<7)return`${diff} days ago`;return d.toLocaleDateString(undefined,{month:'short',day:'numeric'});}
function fmtTime(ts){return new Date(ts).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});}
function fmtDate(ts){return new Date(ts).toLocaleDateString(undefined,{month:'short',day:'numeric',year:new Date(ts).getFullYear()===new Date().getFullYear()?undefined:'numeric'});}
function dayKey(ts){const d=new Date(ts),today=new Date(),y=new Date(Date.now()-86400000);const same=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();if(same(d,today))return'Today';if(same(d,y))return'Yesterday';return d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});}
function ageText(p){return [p.age,p.city,p.occupation].filter(Boolean).join(' · ');}
function avatarTone(p){const tones=['sky','sage','peach','lav','rose'];let n=0;for(const c of p.name||'')n+=c.charCodeAt(0);return tones[n%tones.length];}
function getCurrentRound(s){return round(s?.currentRoundId)}
function shidduchTitle(s){return `${person(s.guyId)?.name||'Guy'} ↔ ${person(s.girlId)?.name||'Girl'}`;}
function linkedAbout(entry){if(entry.aboutType==='person')return person(entry.aboutId)?.name||'Person';if(entry.aboutType==='shidduch')return shidduch(entry.aboutId)?shidduchTitle(shidduch(entry.aboutId)):'Shidduch';if(entry.aboutType==='idea'){const i=idea(entry.aboutId);return i?`${person(i.guyId)?.name} ↔ ${person(i.girlId)?.name}`:'Idea';}if(entry.aboutType==='source')return source(entry.aboutId)?.name||'Source';if(entry.aboutType==='date'){const d=dateById(entry.aboutId),r=round(d?.roundId),s=shidduch(r?.shidduchId);return s?`${shidduchTitle(s)} · Date ${d.number}`:'Date';}return'';}

function sourceStats(src){
  const peopleIds=src.peopleIds||[];let contacted=0,replied=0,follow=0;
  for(const pid of peopleIds){
    const es=entriesForPerson(pid).filter(e=>new Date(e.at)>=new Date(src.createdAt));
    const firstOut=[...es].reverse().find(e=>e.direction==='out');
    if(firstOut){contacted++;const rep=es.find(e=>e.direction==='in'&&new Date(e.at)>new Date(firstOut.at));if(rep)replied++;else{const due=new Date(firstOut.at).getTime()+(src.followUpDays||7)*86400000;if(Date.now()>due)follow++;}}
  }
  return {total:peopleIds.length,contacted,replied,follow,notContacted:peopleIds.length-contacted};
}
function needsContactPerson(p){const es=entriesForPerson(p.id);if(!es.some(e=>e.direction==='out'))return true;for(const src of data.sources.filter(s=>s.peopleIds?.includes(p.id))){const es2=es.filter(e=>new Date(e.at)>=new Date(src.createdAt));const firstOut=[...es2].reverse().find(e=>e.direction==='out');if(firstOut&&!es2.find(e=>e.direction==='in'&&new Date(e.at)>new Date(firstOut.at))&&Date.now()>new Date(firstOut.at).getTime()+(src.followUpDays||7)*86400000)return true;}return false;}
function dormantPerson(p){const lc=lastContact(p.id);return lc&&Date.now()-new Date(lc).getTime()>60*86400000;}

function applySettings(){const s=data.settings||defaultSettings();document.documentElement.dataset.theme=s.theme||'warm';document.documentElement.dataset.density=s.density||'comfortable';document.documentElement.dataset.iconSize=s.iconSize||'medium';const themeColor=s.theme==='dark'?'#151917':s.theme==='blue'?'#f2f6fa':s.theme==='sage'?'#f1f4ef':'#f6f0e7';document.querySelector('meta[name="theme-color"]').setAttribute('content',themeColor);}

function header(title,sub,{add=false,back=false,filter=false}={}){
  return `<header class="screen-head"><div class="head-main">${back?'':`<div class="app-mark"><div class="wordmark">ZivugMatch</div><div class="bh">ב״ה</div></div>`}<div class="screen-title-row">${back?`<button class="back-btn" data-act="back">${icon('back')}</button>`:''}<h1 class="screen-title">${esc(title)}</h1></div>${sub?`<div class="screen-sub">${esc(sub)}</div>`:''}</div><div class="head-actions">${add?`<button class="plus-btn" data-act="add-current" aria-label="Add">${icon('plus')}</button>`:''}${filter?`<button class="icon-btn" data-act="filters" aria-label="Filters">${icon('filter')}</button>`:''}<button class="icon-btn" data-act="settings" aria-label="Settings">${icon('gear')}</button></div></header>`;
}
function searchBox(ph){return `<div class="search-row"><label class="search-box">${icon('search')}<input data-role="search" value="${esc(ui.search)}" placeholder="${esc(ph)}" /></label><button class="filter-btn" data-act="filters" aria-label="Filter and sort">${icon('filter')}</button></div>`;}
function segment(items,active,scope){return `<div class="segment-wrap"><div class="segment">${items.map(x=>`<button class="seg-btn ${x.value===active?'active':''}" data-seg-scope="${scope}" data-seg="${esc(x.value)}">${esc(x.label)}${x.count!=null?` <span class="seg-count">${x.count}</span>`:''}</button>`).join('')}</div></div>`;}
function summaryCard(cls,val,label,act=''){return `<button class="summary-card ${cls}" ${act?`data-act="${act}"`:''}><div class="k">${esc(label)}</div><div class="v">${esc(val)}</div></button>`;}
function empty(title,text,act=''){return `<div class="empty"><div class="empty-icon">${icon('heart')}</div><h3>${esc(title)}</h3><p>${esc(text)}</p>${act?`<button class="primary-btn" data-act="${act}">Add first one</button>`:''}</div>`;}
function nav(){const items=[['recent','recent','Recent'],['guys','guy','Guys'],['girls','girl','Girls'],['shadchanim','shad','Shadchanim'],['shidduchim','heart','Shidduchim']];return `<nav class="bottom-nav">${items.map(([screen,ic,label])=>`<button class="nav-btn ${ui.screen===screen?'active':''}" data-screen="${screen}"><span class="nav-icon-wrap">${icon(ic)}</span><span>${label}</span></button>`).join('')}</nav>`;}
function badge(text,kind='muted'){return text?`<span class="badge ${kind}">${esc(text)}</span>`:'';}

function personRow(p,{selected=false,context=''}={}){
  const them=openForPerson(p.id,'them').length,meCount=openForPerson(p.id,'me').length,active=shidduchimForPerson(p.id).filter(s=>s.status==='active').length,lc=lastContact(p.id);
  let status=[];if(them)status.push(`${them} waiting on them`);if(meCount)status.push(`${meCount} waiting on me`);if(active)status.push(`${active} active`);if(!status.length&&needsContactPerson(p))status.push('Needs contact');
  const line=context||ageText(p)||p.city||p.types?.join(', ')||'';
  return `<button class="list-row ${selected?'selected':''}" data-person="${p.id}"><div class="avatar ${avatarTone(p)}">${esc(initials(p.name))}</div><div class="row-main"><div class="row-top"><div class="row-name">${esc(p.name)}</div><div class="row-time">${esc(fmtDay(lc))}</div></div><div class="row-line">${esc(line)}</div>${status.length?`<div class="row-status">${esc(status.join(' · '))}</div>`:''}</div><div class="row-end">›</div></button>`;
}
function activityIcon(type){const map={call:['phone','sage'],message:['message','sky'],profile:['profile','peach'],date:['calendar','lav'],note:['note','amber'],source:['list','blue'],referral:['link','sage'],status:['check','blue']};return map[type]||['note','blue'];}
function activityRow(e){const [ic,tone]=activityIcon(e.type);let primary=e.type==='call'?'Call':e.type==='message'?e.channel||'Message':e.type==='profile'?'Profile':e.type==='date'?'Date':e.type==='source'?'Source':e.type==='note'?'Note':'Activity';let who='';if(e.direction==='in')who=person(e.fromPersonId)?.name||'';else if(e.direction==='out')who=person(e.toPersonId)?.name||'';else who=e.personIds?.map(pid=>person(pid)?.name).filter(Boolean).join(' · ')||'';return `<button class="list-row activity-row" data-entry="${e.id}"><div class="activity-icon ${tone}">${icon(ic)}</div><div class="row-main"><div class="row-top"><div class="row-name">${esc(who?`${primary} · ${who}`:primary)}</div><div class="row-time">${esc(fmtTime(e.at))}</div></div><div class="row-line">${esc(e.text||'')}</div>${linkedAbout(e)?`<div class="row-status">${esc(linkedAbout(e))}${e.result?` · ${esc(e.result)}`:''}</div>`:''}</div><div class="row-end">›</div></button>`;}

function counts(){return {them:data.openItems.filter(x=>x.status==='open'&&x.direction==='them').length,me:data.openItems.filter(x=>x.status==='open'&&x.direction==='me').length,active:data.shidduchim.filter(x=>x.status==='active').length,ideas:data.ideas.filter(x=>x.status==='open').length,toFile:0};}
function recentScreen(){
  const c=counts(),settings=data.settings;let entries=[...data.entries].sort((a,b)=>new Date(b.at)-new Date(a.at));if(ui.recentFilter!=='all')entries=entries.filter(e=>e.type===ui.recentFilter);if(ui.search){const q=ui.search.toLowerCase();entries=entries.filter(e=>(e.text+' '+linkedAbout(e)+' '+e.personIds?.map(pid=>person(pid)?.name).join(' ')).toLowerCase().includes(q));}
  const groups={};for(const e of entries){const k=dayKey(e.at);(groups[k]??=[]).push(e)}
  const summary=settings.summaryCards?`<div class="summary-strip">${summaryCard('blue',c.me,'Waiting on me','show-wait-me')}${summaryCard('amber',c.them,'Waiting on them','show-wait-them')}${summaryCard('sage',c.active,'Active shidduchim','show-active')}</div>`:'';
  const filters=[['all','All'],['call','Calls'],['message','Messages'],['profile','Profiles'],['date','Dates'],['note','Notes']];
  let feed=Object.entries(groups).map(([day,arr])=>`<div class="day-label">${esc(day)}</div><div class="list-card">${arr.map(activityRow).join('')}</div>`).join('');
  if(!feed)feed=empty('Nothing here yet','Recent will fill itself as you call, message, receive profiles and work on shidduchim.','add-activity');
  const backupText=`Last saved ${fmtTime(data.meta.updatedAt)} · ${data.meta.demo?'Demo data':'Private local data'}`;
  return `${header('Recent',backupText,{add:true})}${summary}${searchBox('Search people, messages, profiles…')}${segment(filters.map(([value,label])=>({value,label})),ui.recentFilter,'recent')}<div class="section-head"><h2>Activity</h2><button data-act="add-activity">Add note</button></div>${feed}`;
}

function filteredPeople(type){let arr=byType(type).filter(p=>!p.isMe);const q=ui.search.trim().toLowerCase();if(q)arr=arr.filter(p=>(`${p.name} ${p.city||''} ${p.occupation||''} ${p.phone||''}`).toLowerCase().includes(q));if(type==='Girl'&&data.settings.mode==='single'){
  const view=ui.screenView.girls;if(view==='for-me')arr=arr.filter(p=>ideasForPerson(p.id).some(i=>i.status==='open'&&(i.guyId===me().id||i.girlId===me().id))||shidduchimForPerson(p.id).some(s=>s.status==='active'&&(s.guyId===me().id||s.girlId===me().id)));if(view==='previous')arr=arr.filter(p=>shidduchimForPerson(p.id).some(s=>s.status==='ended'&&(s.guyId===me().id||s.girlId===me().id))||ideasForPerson(p.id).some(i=>i.status==='not-applicable'&&(i.guyId===me().id||i.girlId===me().id)));
  }
  return arr.sort((a,b)=>(lastContact(b.id)||b.createdAt).localeCompare(lastContact(a.id)||a.createdAt));
}
function peopleScreen(type){const isGirl=type==='Girl',key=isGirl?'girls':'guys';let tabs;if(isGirl&&data.settings.mode==='single')tabs=[{value:'for-me',label:'For me'},{value:'previous',label:'Previous'}];else tabs=[{value:'all',label:'All'},{value:'recent',label:'Recently added'}];const arr=filteredPeople(type);return `${header(isGirl?'Girls':'Guys',isGirl&&data.settings.mode==='single'?'Profiles relevant to you':'Browse and search',{add:true})}${searchBox(`Search ${isGirl?'girls':'guys'}…`)}${segment(tabs,ui.screenView[key],key)}${arr.length?`<div class="list-card">${arr.map((p,i)=>personRow(p,{selected:i===0&&isGirl})).join('')}</div>`:empty(`No ${isGirl?'girls':'guys'} here yet`,`Add a ${isGirl?'girl':'guy'} profile and the app will keep its history, sources and shidduchim together.`,'add-current')}`;}

function shadchanScreen(){const all=byType('Shadchan');const them=all.filter(p=>openForPerson(p.id,'them').length);const mine=all.filter(p=>openForPerson(p.id,'me').length);const needs=all.filter(needsContactPerson);let arr=all;const v=ui.screenView.shadchanim;if(v==='them')arr=them;if(v==='me')arr=mine;if(v==='needs')arr=needs;if(v==='sources')return sourceScreenEmbedded(all.length,them.length,mine.length,needs.length);const q=ui.search.toLowerCase();if(q)arr=arr.filter(p=>(`${p.name} ${p.city||''} ${p.phone||''}`).toLowerCase().includes(q));arr=arr.sort((a,b)=>(lastContact(b.id)||b.createdAt).localeCompare(lastContact(a.id)||a.createdAt));const tabs=[{value:'all',label:'All',count:all.length},{value:'them',label:'Waiting on them',count:them.length},{value:'me',label:'Waiting on me',count:mine.length},{value:'needs',label:'Needs contact',count:needs.length},{value:'sources',label:'Sources',count:data.sources.length}];return `${header('Shadchanim',`${all.length} people · your network`,{add:true})}${searchBox('Search name, phone or city…')}${segment(tabs,v,'shadchanim')}${arr.length?`<div class="list-card">${arr.map((p,i)=>personRow(p,{selected:i===0})).join('')}</div>`:empty('No shadchanim in this view','Nothing needs your attention here right now.')}`;}
function sourceScreenEmbedded(total,them,mine,needs){const tabs=[{value:'all',label:'All',count:total},{value:'them',label:'Waiting on them',count:them},{value:'me',label:'Waiting on me',count:mine},{value:'needs',label:'Needs contact',count:needs},{value:'sources',label:'Sources',count:data.sources.length}];return `${header('Shadchanim',`${total} people · your network`,{add:true})}${searchBox('Search sources…')}${segment(tabs,'sources','shadchanim')}<div class="section-head"><h2>Sources</h2><button data-act="add-source">Add source</button></div>${data.sources.length?`<div class="list-card">${data.sources.map(src=>{const s=sourceStats(src);return `<button class="list-row" data-source="${src.id}"><div class="activity-icon ${src.kind==='event'?'peach':'sky'}">${icon(src.kind==='event'?'calendar':'list')}</div><div class="row-main"><div class="row-top"><div class="row-name">${esc(src.name)}</div><div class="row-time">${esc(fmtDate(src.createdAt))}</div></div><div class="row-line">${s.total} total · ${s.contacted} contacted · ${s.replied} replied</div>${s.follow?`<div class="row-status">${s.follow} needs follow-up</div>`:''}</div><div class="row-end">›</div></button>`}).join('')}</div>`:empty('No sources yet','Lists, events and referrals stay here permanently without duplicating people.','add-source')}`;}

function shidduchimScreen(){const v=ui.screenView.shidduchim;const active=data.shidduchim.filter(s=>s.status==='active'),ended=data.shidduchim.filter(s=>s.status==='ended'),ideas=data.ideas.filter(i=>i.status==='open');const tabs=[{value:'active',label:'Active',count:active.length},{value:'ideas',label:'Ideas',count:ideas.length},{value:'ended',label:'Ended',count:ended.length}];let body='';if(v==='ideas'){body=ideas.length?`<div class="list-card">${ideas.map(i=>{const g=person(i.guyId),gl=person(i.girlId),sug=person(i.suggestedByPersonId);return `<button class="list-row" data-idea="${i.id}"><div class="avatar heart">♡</div><div class="row-main"><div class="row-top"><div class="row-name">${esc(g?.name)} ↔ ${esc(gl?.name)}</div><div class="row-time">${esc(fmtDay(i.createdAt))}</div></div><div class="row-line">Suggested by ${esc(sug?.name||'you')}</div>${badge('Waiting on me','blue')}</div><div class="row-end">›</div></button>`}).join('')}</div>`:empty('No open ideas','An idea is a suggested pair that has not started as a shidduch yet.','add-idea');}else{const arr=v==='active'?active:ended;body=arr.length?`<div class="list-card">${arr.map(s=>{const r=getCurrentRound(s);return `<button class="list-row" data-shidduch="${s.id}"><div class="avatar heart">♥</div><div class="row-main"><div class="row-top"><div class="row-name">${esc(shidduchTitle(s))}</div><div class="row-time">Round ${r?.number||1}</div></div><div class="row-line">${esc(r?.stage||s.status)}</div>${s.status==='active'&&openForShidduch(s.id,'them').length?badge('Waiting on them','amber'):s.status==='ended'?badge('Ended','muted'):badge('Active','sage')}</div><div class="row-end">›</div></button>`}).join('')}</div>`:empty(`No ${v} shidduchim`,v==='active'?'When an idea becomes real, it will appear here.':'Ended shidduchim remain searchable and keep their full history.','add-idea');}
  return `${header('Shidduchim','Actual pairings and ideas',{add:true})}${searchBox('Search a pair…')}${segment(tabs,v,'shidduchim')}${body}`;}
