'use strict';

// Actions: every change to the data goes through these functions. Each writes one ledger entry for what
// happened, changes the records it names, saves once, and then shows the result.

// Adding a person goes through the one matching check: an exact or likely match asks first.
async function savePerson(){const name=document.getElementById('fName')?.value.trim();if(!name)return showToast('Enter a name');const types=[...document.querySelectorAll('input[name="fType"]:checked')].map(x=>x.value);if(!types.length)return showToast('Choose at least one role');const c={name,types,city:document.getElementById('fCity').value.trim(),age:Number(document.getElementById('fAge').value)||undefined,occupation:document.getElementById('fOccupation').value.trim(),phone:document.getElementById('fPhone').value.trim(),email:document.getElementById('fEmail').value.trim(),profile:document.getElementById('fProfile').value.trim()};matchThenUse(c,async(pid,existed)=>{await save();closeSheet();const p=person(pid);ui.detail={type:'person',id:p.id};ui.detailTab=p.types?.includes('Shadchan')?'details':'profile';render();showToast(existed?`Using ${p.name}, already here`:'Person saved');});}
// An activity can settle open items: the ones ticked close, pointing to this entry.
async function saveActivity(){const pid=document.getElementById('aPerson')?.value,type=document.getElementById('aType')?.value,text=document.getElementById('aText')?.value.trim(),who=document.getElementById('aWho')?.value||'none';if(!pid||!text)return showToast('Choose a person and add a note');const direction=['call','message','profile'].includes(type)?who:'none';const sh=shidduch(document.getElementById('aShidduch')?.value),shr=sh&&currentRound(sh);const e=addEntry({type,channel:type==='call'?'Call':type==='message'?'Message':'App',direction,fromPersonId:direction==='in'?pid:direction==='out'?me().id:null,toPersonId:direction==='in'?me().id:direction==='out'?pid:null,personIds:sh?[pid,sh.guyId,sh.girlId]:[pid],about:sh?[{type:'shidduch',id:sh.id},...(shr?[{type:'round',id:shr.id}]:[]),{type:'person',id:pid}]:[{type:'person',id:pid}],text});for(const box of document.querySelectorAll('input[name="activitySettles"]:checked')){const x=openItem(box.value);if(x?.status==='open'){closeItemRecord(x,{entryId:e.id,kind:x.direction==='them'?'heard-back':'done',at:e.at});e.changes.push({kind:'item-closed',itemId:x.id});}}await save();closeSheet();render();showToast('Activity saved');}

// An offer is a suggested pair, not a shidduch. An offer for me opens "answer the one who suggested it";
// with no suggester there is nobody to answer, so no item opens.
async function saveIdea(){const guyId=document.getElementById('iGuy').value,girlId=document.getElementById('iGirl').value,by=document.getElementById('iBy').value;if(!guyId||!girlId||guyId===girlId)return showToast('Choose a guy and a girl');const existing=data.ideas.find(i=>samePerson(i.guyId,guyId)&&samePerson(i.girlId,girlId)&&i.status==='open');if(existing){closeSheet();ideaSheet(existing.id);return;}const i={id:id('idea'),guyId,girlId,suggestedByPersonId:by||null,createdAt:iso(),status:'open',privateReason:''};const pair=shidduchForPair(guyId,girlId);if(pair)i.shidduchId=pair.id;data.ideas.push(i);const e=addEntry({type:'status',personIds:[guyId,girlId,by],about:[{type:'idea',id:i.id}],text:`Idea created: ${person(guyId).name} ↔ ${person(girlId).name}.`,result:'Idea',changes:[{kind:'idea-opened',ideaId:i.id}]});i.openedByEntryId=e.id;if(by&&(isMe(guyId)||isMe(girlId)))addOpenItem({direction:'me',personId:by,about:{type:'idea',id:i.id},kind:'answer-offer',label:`Answer about ${isMe(guyId)?person(girlId).name:person(guyId).name}`,openedByEntryId:e.id});await save();closeSheet();ui.screen='shidduchim';ui.screenView.shidduchim='ideas';render();showToast('Offer saved');}

// WhatsApp needs the international form: Israeli local numbers (05x…, 0x…) become 972…, and a 00 prefix is dropped.
function waNumber(phone){let d=phoneDigits(phone);if(d.startsWith('00'))d=d.slice(2);else if(d.startsWith('0'))d='972'+d.slice(1);return d;}
function contactUrl(p,kind){if(kind==='call'&&phoneDigits(p.phone))return`tel:${p.phone}`;if(kind==='sms'&&phoneDigits(p.phone))return`sms:${p.phone}`;if(kind==='email'&&p.email)return`mailto:${encodeURIComponent(p.email)}`;if(kind==='wa'&&phoneDigits(p.phone))return`whatsapp://send?phone=${waNumber(p.phone)}`;return'';}
// A contact is written to the history only when the app actually opens the call, message or email.
// With open items, the app then asks what the contact settled (shown when you come back).
async function logContact(pid,kind){const p=person(pid);if(!p)return;const channel=kind==='call'?'Call':kind==='wa'?'WhatsApp':kind==='sms'?'SMS':'Email';const url=contactUrl(p,kind);if(!url){showToast(`Add ${kind==='email'?'an email':'a phone number'} to use ${channel}`);return;}const e=addEntry({type:kind==='call'?'call':'message',channel,direction:'out',fromPersonId:me().id,toPersonId:p.id,personIds:[me().id,p.id],about:[{type:'person',id:p.id}],text:`${channel} opened.`});await save();render();afterContactSheet(p.id,e.id);location.href=url;}

// Backups: one JSON file with every record, the settings and every file's content.
async function exportBackup(){try{const obj=await backupObject();const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ZivugMatch_${APP_VERSION_LABEL}_Backup_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Backup exported');}catch(e){console.error(e);showToast('Could not export the backup');}}
async function importBackup(file){let incoming;try{incoming=readBackupObject(JSON.parse(await file.text()));}catch(e){showToast('Could not restore this file');return;}const copyId=await keepSafetyCopy('restoring a backup');for(const [fid,url] of Object.entries(incoming.blobs||{})){try{await putBlob(fid,await dataUrlToBlob(url));}catch(e){}}data=incoming.data;await save();closeSheet();ui.detail=null;ui.screen='recent';render();showUndoToast('Backup restored',copyId);}

function openAbout(entry){const a=entry.about?.[0];if(!a)return;if(a.type==='person')ui.detail={type:'person',id:canonId(a.id)};else if(a.type==='shidduch')ui.detail={type:'shidduch',id:shidduch(a.id)?.id||a.id};else if(a.type==='round'){const r=round(a.id);if(r)ui.detail={type:'shidduch',id:shidduch(r.shidduchId)?.id||r.shidduchId};}else if(a.type==='source')ui.detail={type:'source',id:a.id};else if(a.type==='idea'){closeSheet();ideaSheet(a.id);return;}else if(a.type==='date'){const d=dateById(a.id);const sid=d?.shidduchId||round(d?.roundId)?.shidduchId;if(sid)ui.detail={type:'shidduch',id:shidduch(sid)?.id||sid};}ui.detailTab='overview';render();}
