

async function savePerson(){const name=document.getElementById('fName')?.value.trim();if(!name)return showToast('Enter a name');const types=[...document.querySelectorAll('input[name="fType"]:checked')].map(x=>x.value);if(!types.length)return showToast('Choose at least one role');const p={id:id('p'),name,types,city:document.getElementById('fCity').value.trim(),age:Number(document.getElementById('fAge').value)||undefined,occupation:document.getElementById('fOccupation').value.trim(),phone:document.getElementById('fPhone').value.trim(),email:document.getElementById('fEmail').value.trim(),profileText:document.getElementById('fProfile').value.trim(),profileVersion:1,createdAt:iso()};const dup=data.people.find(x=>String(x.name||'').toLowerCase()===name.toLowerCase()||(p.phone&&phoneDigits(x.phone)===phoneDigits(p.phone)));if(dup){showToast(`${dup.name} is likely already here`);ui.detail={type:'person',id:dup.id};ui.detailTab=dup.types?.includes('Shadchan')?'details':'profile';closeSheet();render();return;}data.people.push(p);data.entries.push({id:id('e'),at:iso(),type:'note',channel:'App',direction:'none',personIds:[p.id],aboutType:'person',aboutId:p.id,text:`Added ${p.name}.`,result:''});await save();closeSheet();ui.detail={type:'person',id:p.id};ui.detailTab=p.types.includes('Shadchan')?'details':'profile';render();showToast('Person saved');}
async function saveActivity(){const pid=document.getElementById('aPerson')?.value,type=document.getElementById('aType')?.value,text=document.getElementById('aText')?.value.trim();if(!pid||!text)return showToast('Choose a person and add a note');data.entries.push({id:id('e'),at:iso(),type,channel:type==='call'?'Call':type==='message'?'Message':'App',direction:'none',personIds:[pid],aboutType:'person',aboutId:pid,text,result:''});await save();closeSheet();render();showToast('Activity saved');}
async function saveIdea(){const guyId=document.getElementById('iGuy').value,girlId=document.getElementById('iGirl').value,by=document.getElementById('iBy').value;if(!guyId||!girlId||guyId===girlId)return showToast('Choose a guy and a girl');const existing=data.ideas.find(i=>i.guyId===guyId&&i.girlId===girlId&&i.status==='open');if(existing){closeSheet();ideaSheet(existing.id);return;}const i={id:id('idea'),guyId,girlId,suggestedByPersonId:by||undefined,createdAt:iso(),status:'open',privateReason:''};data.ideas.push(i);data.entries.push({id:id('e'),at:iso(),type:'status',channel:'App',direction:'none',personIds:[guyId,girlId,...(by?[by]:[])],aboutType:'idea',aboutId:i.id,text:`Idea created: ${person(guyId).name} ↔ ${person(girlId).name}.`,result:'Idea'});if(guyId===me().id||girlId===me().id)data.openItems.push({id:id('oi'),direction:'me',personId:by||girlId,aboutType:'idea',aboutId:i.id,label:`Answer about ${guyId===me().id?person(girlId).name:person(guyId).name}`,createdAt:iso(),status:'open'});await save();closeSheet();ui.screen='shidduchim';ui.screenView.shidduchim='ideas';render();showToast('Idea saved');}
async function saveSource(){const name=document.getElementById('sName').value.trim();if(!name)return showToast('Enter a source name');data.sources.push({id:id('src'),name,kind:document.getElementById('sKind').value,createdAt:iso(),peopleIds:[],followUpDays:Number(document.getElementById('sDays').value)||7});await save();closeSheet();render();showToast('Source saved');}
async function chooseIdea(iid,yes){const i=idea(iid);if(!i||i.status!=='open')return;if(!yes){i.status='not-applicable';i.closedAt=iso();data.openItems.filter(x=>x.aboutType==='idea'&&x.aboutId===i.id).forEach(x=>{x.label=`Tell ${person(i.suggestedByPersonId)?.name||'the shadchan'}: not applicable`;x.direction='me';});data.entries.push({id:id('e'),at:iso(),type:'status',channel:'App',direction:'none',personIds:[i.guyId,i.girlId],aboutType:'idea',aboutId:i.id,text:'Marked not applicable.',result:'Not applicable'});await save();closeSheet();render();showToast('Idea closed');return;}i.status='converted';i.closedAt=iso();let s=data.shidduchim.find(s=>s.guyId===i.guyId&&s.girlId===i.girlId);if(!s){s={id:id('sh'),guyId:i.guyId,girlId:i.girlId,createdAt:iso(),status:'active',suggestedByPersonId:i.suggestedByPersonId,shadchanIds:i.suggestedByPersonId?[i.suggestedByPersonId]:[],private:i.guyId===me().id||i.girlId===me().id};data.shidduchim.push(s);}const current=getCurrentRound(s),continuing=current?.status==='active';let r=current;if(!continuing){const existingRounds=data.rounds.filter(x=>x.shidduchId===s.id);r={id:id('round'),shidduchId:s.id,number:Math.max(0,...existingRounds.map(x=>Number(x.number)||0))+1,createdAt:iso(),status:'active',guyStatus:i.guyId===me().id?'yes':'unknown',girlStatus:'unknown',stage:'Waiting for other side'};data.rounds.push(r);s.currentRoundId=r.id;}s.status='active';data.openItems.filter(x=>x.aboutType==='idea'&&x.aboutId===i.id).forEach(x=>x.status='closed');if(i.suggestedByPersonId&&!data.openItems.some(x=>x.status==='open'&&x.direction==='them'&&x.personId===i.suggestedByPersonId&&x.aboutType==='shidduch'&&x.aboutId===s.id))data.openItems.push({id:id('oi'),direction:'them',personId:i.suggestedByPersonId,aboutType:'shidduch',aboutId:s.id,label:'Other side answer',createdAt:iso(),status:'open'});data.entries.push({id:id('e'),at:iso(),type:'status',channel:'App',direction:'none',personIds:[i.guyId,i.girlId,...(i.suggestedByPersonId?[i.suggestedByPersonId]:[])],aboutType:'shidduch',aboutId:s.id,text:continuing?`Interested again. Round ${r.number} continues.`:`Interested. Round ${r.number} started.`,result:'Shidduch active'});await save();closeSheet();ui.detail={type:'shidduch',id:s.id};ui.detailTab='overview';render();showToast(continuing?'Shidduch already in progress':'Shidduch started');}

// Completing an open item closes exactly that item and writes what happened to the history.
async function closeOpenItem(itemId){const x=data.openItems.find(v=>v.id===itemId&&v.status==='open');if(!x)return;const heard=x.direction==='them';const e={id:id('e'),at:iso(),type:'status',channel:'App',direction:'none',personIds:[x.personId].filter(Boolean),aboutType:x.aboutType,aboutId:x.aboutId,text:`${heard?'Heard back':'Done'}: ${x.label}`,result:heard?'Heard back':'Done'};data.entries.push(e);x.status='closed';x.closedAt=e.at;x.closedByEntryId=e.id;await save();closeSheet();render();showActionToast(heard?'Marked as heard back':'Marked as done',{act:'undo-close-item',itemId:x.id,entryId:e.id});}
async function undoCloseOpenItem(itemId,entryId){const x=data.openItems.find(v=>v.id===itemId);if(!x||x.closedByEntryId!==entryId)return;x.status='open';delete x.closedAt;delete x.closedByEntryId;data.entries=data.entries.filter(e=>e.id!==entryId);await save();render();showToast('Reopened');}
// WhatsApp needs the international form: Israeli local numbers (05x…, 0x…) become 972…, and a 00 prefix is dropped.
function waNumber(phone){let d=phoneDigits(phone);if(d.startsWith('00'))d=d.slice(2);else if(d.startsWith('0'))d='972'+d.slice(1);return d;}
function contactUrl(p,kind){if(kind==='call'&&phoneDigits(p.phone))return`tel:${p.phone}`;if(kind==='sms'&&phoneDigits(p.phone))return`sms:${p.phone}`;if(kind==='email'&&p.email)return`mailto:${encodeURIComponent(p.email)}`;if(kind==='wa'&&phoneDigits(p.phone))return`whatsapp://send?phone=${waNumber(p.phone)}`;return'';}
// A contact is written to the history only when the app actually opens the call, message or email.
async function logContact(pid,kind){const p=person(pid);if(!p)return;const channel=kind==='call'?'Call':kind==='wa'?'WhatsApp':kind==='sms'?'SMS':'Email';const url=contactUrl(p,kind);if(!url){showToast(`Add ${kind==='email'?'an email':'a phone number'} to use ${channel}`);return;}data.entries.push({id:id('e'),at:iso(),type:kind==='call'?'call':'message',channel,direction:'out',fromPersonId:me().id,toPersonId:p.id,personIds:[me().id,p.id],aboutType:'person',aboutId:p.id,text:`${channel} opened.`,result:''});await save();render();location.href=url;}

function exportBackup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ZivugMatch_Backup_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Backup exported');}
async function importBackup(file){try{const obj=JSON.parse(await file.text());if(!Array.isArray(obj.people)||!Array.isArray(obj.entries)||!obj.settings)throw new Error('Not a ZivugMatch backup');normalizeData(obj);const copyId=await keepSafetyCopy('restoring a backup');data=obj;await save();closeSheet();ui.detail=null;ui.screen='recent';render();showUndoToast('Backup restored',copyId);}catch(e){showToast('Could not restore this file');}}

function openAbout(entry){if(entry.aboutType==='person')ui.detail={type:'person',id:entry.aboutId};else if(entry.aboutType==='shidduch')ui.detail={type:'shidduch',id:entry.aboutId};else if(entry.aboutType==='source')ui.detail={type:'source',id:entry.aboutId};else if(entry.aboutType==='idea'){closeSheet();ideaSheet(entry.aboutId);return;}else if(entry.aboutType==='date'){const d=dateById(entry.aboutId),r=round(d?.roundId);if(r)ui.detail={type:'shidduch',id:r.shidduchId};}ui.detailTab='overview';render();}
